# Generated by Django 3.2.7 on 2021-09-27 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gallery.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('img_file', models.ImageField(upload_to=gallery.models.user_directory_path)),
                ('img_thumb', models.ImageField(blank=True, upload_to='media/')),
                ('img_s', models.ImageField(blank=True, upload_to='media/')),
                ('img_m', models.ImageField(blank=True, upload_to='media/')),
                ('img_l', models.ImageField(blank=True, upload_to='media/')),
                ('pub_date', models.DateTimeField(blank=True)),
                ('order_num', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
